package com.sophon.autoyantra.generator;

import com.sophon.autoyantra.util.AYContext;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JTextField;

public class ConfigGenerator {
    public static void generateConfig(String currentModuleName, Map<String, JComponent> currentWidgets, DefaultListModel<String> generationErrorsModel) {
        if (currentModuleName == null) {
            generationErrorsModel.addElement("Error: No module selected.");
            return;
 }
        String baseDir = AYContext.getInstance().workspacePath + "/modules/" + currentModuleName + "/";
        String[] configTypes = {"PB", "PC"}; 

        for (String configType : configTypes) {
            Path templateDir = Paths.get(baseDir, "templates", configType);
            if (!Files.exists(templateDir)) {
                generationErrorsModel.addElement("No templates found in " + configType + " folder.");
                continue;
            }
            try (DirectoryStream<Path> stream = Files.newDirectoryStream(templateDir)) {
                for (Path templatePath : stream) {
                    String fileName = templatePath.getFileName().toString();
                    if (fileName.endsWith(".h") || fileName.endsWith(".c")) {
                        processTemplate(templatePath, currentWidgets, generationErrorsModel);
                    }
                }
            } catch (IOException e) {
                generationErrorsModel.addElement("Error reading " + configType + " templates: " + e.getMessage());
            }
        }
    }

    private static void processTemplate(Path templatePath, Map<String, JComponent> currentWidgets, DefaultListModel<String> errors) {
        try {
            String templateText = new String(Files.readAllBytes(templatePath));
            String outputName = templatePath.getFileName().toString(); 
            
            for (Map.Entry<String, JComponent> entry : currentWidgets.entrySet()) {
                String placeholder = "${" + entry.getKey() + "}";
                String value = AYContext.getInstance().getWidgetValue(entry.getValue());
                templateText = templateText.replace(placeholder, value);
            }

            if (outputName.endsWith(".h")) templateText = addHeaderGuard(outputName, templateText);
            if (outputName.endsWith(".c")) templateText = addCFileBanner(outputName, templateText);

            if (templateText.contains("${")) {
                int start = templateText.indexOf("${");
                int end = templateText.indexOf("}", start);
                errors.addElement("Unresolved placeholder: " + templateText.substring(start, end + 1));
            }

            // Smart routing: .h goes to include/, .c goes to src/
            Path moduleDir = templatePath.getParent().getParent().getParent();
            Path outputDir = outputName.endsWith(".h") ? moduleDir.resolve("include") : moduleDir.resolve("src");

            // Ensure the target directory exists
            java.nio.file.Files.createDirectories(outputDir);

            Path outputPath = outputDir.resolve(outputName);
            Files.write(outputPath, templateText.getBytes());
            errors.addElement("Generated: " + outputPath.toString());
        } catch (Exception e) {
            errors.addElement("Error processing " + templatePath.getFileName() + ": " + e.getMessage());
        }
    }

    private static String addHeaderGuard(String fileName, String content) {
        String guardName = fileName.replace(".", "_").toUpperCase() + "_H";
        StringBuilder header = new StringBuilder();
        header.append("/**\n * @file ").append(fileName).append("\n * @brief Auto-generated by AutoYantra v1.0\n * @warning DO NOT EDIT\n */\n\n");
        header.append("#ifndef ").append(guardName).append("\n#define ").append(guardName).append("\n\n").append(content).append("\n#endif /* ").append(guardName).append(" */\n");
        return header.toString();
    }

    private static String addCFileBanner(String fileName, String content) {
        StringBuilder header = new StringBuilder();
        header.append("/**\n * @file ").append(fileName).append("\n * @brief Auto-generated by AutoYantra v1.0\n * @warning DO NOT EDIT\n */\n\n");
        header.append("#include \"").append(fileName.replace(".c", ".h")).append("\"\n\n").append(content);
        return header.toString();
    }

    public static void verifyProject(Map<String, JComponent> currentWidgets, Map<String, String> currentParamTypes,
                                     Map<String, String> currentParamMin, Map<String, String> currentParamMax,
                                     DefaultListModel<String> configIssuesModel) {
        configIssuesModel.clear();
        for (Map.Entry<String, JComponent> entry : currentWidgets.entrySet()) {
            String name = entry.getKey();
            JComponent comp = entry.getValue();
            String type = currentParamTypes.get(name);
            if ("int".equals(type) && comp instanceof JTextField) {
                String text = ((JTextField) comp).getText();
                try {
                    int value = Integer.parseInt(text);
                    String minStr = currentParamMin != null ? currentParamMin.get(name) : null;
                    String maxStr = currentParamMax != null ? currentParamMax.get(name) : null;
                    if (minStr != null && !minStr.isEmpty() && value < Long.parseLong(minStr)) 
                        configIssuesModel.addElement(name + ": " + value + " is below minimum " + minStr);
                    if (maxStr != null && !maxStr.isEmpty() && value > Long.parseLong(maxStr)) 
                        configIssuesModel.addElement(name + ": " + value + " is above maximum " + maxStr);
                } catch (NumberFormatException ex) {
                    configIssuesModel.addElement(name + ": \"" + text + "\" is not a valid integer");
                }
            }
        }
        if (configIssuesModel.isEmpty()) configIssuesModel.addElement("No issues found.");
    }
}